version: '3'

services:
  postbase:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env.local
    volumes:
      - ./data/sql/ddl/tables_ddl.sql:/docker-entrypoint-initdb.d/tables_ddl.sql
  webserver:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postbase